require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntrantsController do

  # This should return the minimal set of attributes required to create a valid
  # Entrant. As you add validations to Entrant, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all entrants as @entrants" do
      entrant = Entrant.create! valid_attributes
      get :index
      assigns(:entrants).should eq([entrant])
    end
  end

  describe "GET show" do
    it "assigns the requested entrant as @entrant" do
      entrant = Entrant.create! valid_attributes
      get :show, :id => entrant.id
      assigns(:entrant).should eq(entrant)
    end
  end

  describe "GET new" do
    it "assigns a new entrant as @entrant" do
      get :new
      assigns(:entrant).should be_a_new(Entrant)
    end
  end

  describe "GET edit" do
    it "assigns the requested entrant as @entrant" do
      entrant = Entrant.create! valid_attributes
      get :edit, :id => entrant.id
      assigns(:entrant).should eq(entrant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Entrant" do
        expect {
          post :create, :entrant => valid_attributes
        }.to change(Entrant, :count).by(1)
      end

      it "assigns a newly created entrant as @entrant" do
        post :create, :entrant => valid_attributes
        assigns(:entrant).should be_a(Entrant)
        assigns(:entrant).should be_persisted
      end

      it "redirects to the created entrant" do
        post :create, :entrant => valid_attributes
        response.should redirect_to(Entrant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entrant as @entrant" do
        # Trigger the behavior that occurs when invalid params are submitted
        Entrant.any_instance.stub(:save).and_return(false)
        post :create, :entrant => {}
        assigns(:entrant).should be_a_new(Entrant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Entrant.any_instance.stub(:save).and_return(false)
        post :create, :entrant => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entrant" do
        entrant = Entrant.create! valid_attributes
        # Assuming there are no other entrants in the database, this
        # specifies that the Entrant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Entrant.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => entrant.id, :entrant => {'these' => 'params'}
      end

      it "assigns the requested entrant as @entrant" do
        entrant = Entrant.create! valid_attributes
        put :update, :id => entrant.id, :entrant => valid_attributes
        assigns(:entrant).should eq(entrant)
      end

      it "redirects to the entrant" do
        entrant = Entrant.create! valid_attributes
        put :update, :id => entrant.id, :entrant => valid_attributes
        response.should redirect_to(entrant)
      end
    end

    describe "with invalid params" do
      it "assigns the entrant as @entrant" do
        entrant = Entrant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Entrant.any_instance.stub(:save).and_return(false)
        put :update, :id => entrant.id, :entrant => {}
        assigns(:entrant).should eq(entrant)
      end

      it "re-renders the 'edit' template" do
        entrant = Entrant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Entrant.any_instance.stub(:save).and_return(false)
        put :update, :id => entrant.id, :entrant => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entrant" do
      entrant = Entrant.create! valid_attributes
      expect {
        delete :destroy, :id => entrant.id
      }.to change(Entrant, :count).by(-1)
    end

    it "redirects to the entrants list" do
      entrant = Entrant.create! valid_attributes
      delete :destroy, :id => entrant.id
      response.should redirect_to(entrants_url)
    end
  end

end
