require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrapSpeedsController do

  # This should return the minimal set of attributes required to create a valid
  # TrapSpeed. As you add validations to TrapSpeed, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all trap_speeds as @trap_speeds" do
      trap_speed = TrapSpeed.create! valid_attributes
      get :index
      assigns(:trap_speeds).should eq([trap_speed])
    end
  end

  describe "GET show" do
    it "assigns the requested trap_speed as @trap_speed" do
      trap_speed = TrapSpeed.create! valid_attributes
      get :show, :id => trap_speed.id
      assigns(:trap_speed).should eq(trap_speed)
    end
  end

  describe "GET new" do
    it "assigns a new trap_speed as @trap_speed" do
      get :new
      assigns(:trap_speed).should be_a_new(TrapSpeed)
    end
  end

  describe "GET edit" do
    it "assigns the requested trap_speed as @trap_speed" do
      trap_speed = TrapSpeed.create! valid_attributes
      get :edit, :id => trap_speed.id
      assigns(:trap_speed).should eq(trap_speed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TrapSpeed" do
        expect {
          post :create, :trap_speed => valid_attributes
        }.to change(TrapSpeed, :count).by(1)
      end

      it "assigns a newly created trap_speed as @trap_speed" do
        post :create, :trap_speed => valid_attributes
        assigns(:trap_speed).should be_a(TrapSpeed)
        assigns(:trap_speed).should be_persisted
      end

      it "redirects to the created trap_speed" do
        post :create, :trap_speed => valid_attributes
        response.should redirect_to(TrapSpeed.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trap_speed as @trap_speed" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrapSpeed.any_instance.stub(:save).and_return(false)
        post :create, :trap_speed => {}
        assigns(:trap_speed).should be_a_new(TrapSpeed)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrapSpeed.any_instance.stub(:save).and_return(false)
        post :create, :trap_speed => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trap_speed" do
        trap_speed = TrapSpeed.create! valid_attributes
        # Assuming there are no other trap_speeds in the database, this
        # specifies that the TrapSpeed created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TrapSpeed.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => trap_speed.id, :trap_speed => {'these' => 'params'}
      end

      it "assigns the requested trap_speed as @trap_speed" do
        trap_speed = TrapSpeed.create! valid_attributes
        put :update, :id => trap_speed.id, :trap_speed => valid_attributes
        assigns(:trap_speed).should eq(trap_speed)
      end

      it "redirects to the trap_speed" do
        trap_speed = TrapSpeed.create! valid_attributes
        put :update, :id => trap_speed.id, :trap_speed => valid_attributes
        response.should redirect_to(trap_speed)
      end
    end

    describe "with invalid params" do
      it "assigns the trap_speed as @trap_speed" do
        trap_speed = TrapSpeed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrapSpeed.any_instance.stub(:save).and_return(false)
        put :update, :id => trap_speed.id, :trap_speed => {}
        assigns(:trap_speed).should eq(trap_speed)
      end

      it "re-renders the 'edit' template" do
        trap_speed = TrapSpeed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrapSpeed.any_instance.stub(:save).and_return(false)
        put :update, :id => trap_speed.id, :trap_speed => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trap_speed" do
      trap_speed = TrapSpeed.create! valid_attributes
      expect {
        delete :destroy, :id => trap_speed.id
      }.to change(TrapSpeed, :count).by(-1)
    end

    it "redirects to the trap_speeds list" do
      trap_speed = TrapSpeed.create! valid_attributes
      delete :destroy, :id => trap_speed.id
      response.should redirect_to(trap_speeds_url)
    end
  end

end
